#####
# Travis CI
#
# After changing this file, check it on:
# http://lint.travis-ci.org/

language: node_js
# Is `sudo` required? If not, jobs are run on container-based infrastructure.
sudo: required
dist: trusty
node_js:
  - "stable"
  - "5"
matrix:
  fast_finish: true

addons:
  apt:
    sources:
      # needed to install g++ that is used by npms's native modules
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++-4.8
      - google-chrome-stable

cache:
  directories:
    - node_modules

install:
  - ./scripts/build.sh

script:
  - ./scripts/coverage.sh

after_success:
  - ./scripts/after.sh

notifications:
  email:
    on_success: change
    on_failure: change
